# Generated by Django 4.2.6 on 2023-10-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check_Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(unique=True, verbose_name='ID канала')),
            ],
            options={
                'verbose_name': 'канал',
                'verbose_name_plural': 'Каналы телеграмм',
                'db_table': 'check_channels',
            },
        ),
        migrations.CreateModel(
            name='Check_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups_id', models.IntegerField(unique=True, verbose_name='ID группы')),
            ],
            options={
                'verbose_name': 'группу',
                'verbose_name_plural': 'Группы телеграмм',
                'db_table': 'check_groups',
            },
        ),
        migrations.CreateModel(
            name='Maillings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('photo', models.ImageField(null=True, upload_to='maillings_image/', verbose_name='Фотография')),
                ('get_on_send', models.BooleanField(default=False, verbose_name='Взято в отправку')),
                ('finished', models.BooleanField(default=False, verbose_name='Отправка закончена')),
            ],
            options={
                'verbose_name': 'рассылку',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'maillings',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(null=True, verbose_name='Ответ')),
                ('count', models.IntegerField(verbose_name='Колличество похожих вопросов')),
            ],
            options={
                'verbose_name': 'вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(unique=True, verbose_name='Индификатор телеграмм')),
                ('admin', models.BooleanField(default=False, verbose_name='Админ пользователь')),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Addresses_Deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_models.users')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'Адреса',
                'db_table': 'addresses_deliver',
            },
        ),
    ]
