version: '3.8'

services:
  django_admin:
    image: krymmy/btest_djadmi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/django_admin/web/staticfiles
      - media_volume:/home/app/django_admin/web/mediafiles
    expose:
      - 8000:8000
    env_file:
      - ./.env.prod.django
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/django_admin/staticfiles
      - media_volume:/home/app/django_admin/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - django_admin

volumes:
  postgres_data:
  static_volume:
  media_volume:
