# Generated by Django 4.2.6 on 2023-10-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
                'db_table': 'basket_items',
            },
        ),
        migrations.CreateModel(
            name='Baskets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'корзина',
                'verbose_name_plural': 'Корзины',
                'db_table': 'baskets',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Payment_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'сервис платежа',
                'verbose_name_plural': 'Сервисы платежа',
                'db_table': 'payment_service',
            },
        ),
        migrations.CreateModel(
            name='Payment_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'статус платежа',
                'verbose_name_plural': 'Статусы платежа',
                'db_table': 'payment_status',
            },
        ),
        migrations.CreateModel(
            name='Sub_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='Номер категории')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='Oders',
            fields=[
                ('order_id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('address_deliver', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_service_data', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.baskets')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.payment_service')),
                ('payment_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.payment_status')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='items_images/', verbose_name='Фотография')),
                ('name', models.CharField(max_length=100, verbose_name='Имя товара')),
                ('count', models.IntegerField(verbose_name='Колличество на складе')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sub_categories', verbose_name='Номер подкатегории')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'items',
            },
        ),
        migrations.AddField(
            model_name='baskets',
            name='basket_store',
            field=models.ManyToManyField(through='products.Basket_Items', to='products.items'),
        ),
        migrations.AddField(
            model_name='baskets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_models.users'),
        ),
        migrations.AddField(
            model_name='basket_items',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.baskets'),
        ),
        migrations.AddField(
            model_name='basket_items',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.items'),
        ),
    ]
