from os import getenv
from dotenv import load_dotenv

DEBUG = load_dotenv(".env")


ASTERISK_ARI_URL=getenv("ASTERISK_ARI_URL")
ASTERISK_ARI_LOGIN=getenv("ASTERISK_ARI_LOGIN")
ASTERISK_ARI_PASSWORD=getenv("ASTERISK_ARI_PASSWORD")
ASTERISK_APP_NAME=getenv("ASTERISK_APP_NAME")
ASTERISK_CALL_ENDPOINT=getenv("ASTERISK_CALL_ENDPOINT")

PLAYBACK_STORAGE=getenv("PLAYBACK_STORAGE")

RECORD_STORAGE=getenv("RECORD_STORAGE")


YANDEX_TOKEN=getenv("YANDEX_TOKEN")
YANDEX_FOLDERID=getenv("YANDEX_FOLDERID")

TOKEN_TYPE = getenv("TOKEN_TYPE")
